### ISSUE TITLE
Unsupported Node version in example/apigw

### ISSUE THREAD

**Issue by conormiley** [amaysim-au/docker-serverless#36]
The `serverless.yml`  in the `example/apigw` contains a reference to an unsupported version of Node.js.  This prevents the example from deploying successfully.

This should be updated to the latest supported version of Node.js for the Lambda Runtime as specified here: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html 

```
service: amaysim-apigw-example
package:
  artifact: package/package.zip
provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:AWS_REGION}
  stage: ${env:ENV}
```
